version: '3.4'

services:
  app:
    image: todo-app
    container_name: todo-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    depends_on:
      - postgres
    volumes:
      - ./.bin/:/root/
      - ./configs/:/root/configs/
      - ./templates/:/root/templates/
    env_file:
      - .env

  postgres:
    image: "postgres:alpine"
    container_name: todo-app-db
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=postgres
    volumes:
      - ./.data/db:/data/db
    env_file:
      - .env
    ports:
      - "5432:5432"